/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tuandhpc05076.DangNhap;

import com.tuandhpc05076.Dao.NhanVienDAO;
import static com.tuandhpc05076.Form.NhanVien.list;
import com.tuandhpc05076.MaHoa.MaHoa;
import com.tuandhpc05076.Object.O_DangNhap;
import com.tuandhpc05076.Object.O_NhanVien;
import com.tuandhpc05076.helper.DialogHelper;
import com.tuandhpc05076.helper.ShareHelper;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

public class Login extends PanelCustom {

    public static ArrayList<O_DangNhap> list1 = new ArrayList<>();
    private EventLogin event;
    O_DangNhap dn = new O_DangNhap();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDangNhap = new com.tuandhpc05076.Swing.Button();
        txtPass = new com.tuandhpc05076.DangNhap.Password();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new com.tuandhpc05076.Swing.TextField1();

        setBackground(new java.awt.Color(85, 193, 217));

        btnDangNhap.setBackground(new java.awt.Color(0, 0, 255));
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setHint("Nhập mật khẩu");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng nhập");

        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setHint("Nhập mã");
        txtUserName.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public boolean kiem() {
        if (txtUserName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã");
            return false;
        }
        if (new String(txtPass.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this, "Mật khẩu của bạn đã để trống");
            return false;
        }
        return true;
    }
    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (kiem() == false) {
            return;
        }
        list1.clear();
        MaHoa ma = new MaHoa();
        String pass = ma.toSHA(new String(txtPass.getPassword()));
        dn.getThongtin(txtUserName, new JPasswordField(pass));
        dn.getAlllist();
        int chon = 1;
        System.out.println(list1.size());
        if (list1.size() > 0) {
            JOptionPane.showMessageDialog(this, "Login succesfully!");
            com.tuandhpc05076.Main.Main m = new com.tuandhpc05076.Main.Main();
            m.setVisible(true);
            txtUserName.setText("");
            txtPass.setText("");
            chon = 2;

        }

        if (chon == 1) {
            JOptionPane.showMessageDialog(this, "Login Falled!");

        }


    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseExited
        btnDangNhap.setBackground(new Color(0, 0, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhapMouseExited

    private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
        // TODO add your handling code here:
        btnDangNhap.setBackground(Color.pink);
    }//GEN-LAST:event_btnDangNhapMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tuandhpc05076.Swing.Button btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private com.tuandhpc05076.DangNhap.Password txtPass;
    private com.tuandhpc05076.Swing.TextField1 txtUserName;
    // End of variables declaration//GEN-END:variables
}
